- name: frontend setup
  hosts: all
  become: true
  tasks:
    - name: Install nginx 1.24
      ansible.builtin.dnf:
        name: '@nginx:1.24'
        state: present

    - name: Remove default html content
      ansible.builtin.file:
        path: /usr/share/nginx/html
        state: absent

    - name: create a html directory
      ansible.builtin.file:
        path: /usr/share/nginx/html
        state: directory

    - name: download and extract app content
      ansible.builtin.unarchive:
        src: https://roboshop-artifacts.s3.amazonaws.com/frontend-v3.zip
        dest: /usr/share/nginx/html
        remote_src: yes

    - name: Copy nginx config file
      ansible.builtin.copy:
        src: nginx.conf
        dest: /etc/nginx/nginx.conf

    - name: Start nginx service
      ansible.builtin.systemd_service:
        state: restarted
        name: nginx
        enabled: true