#cp mongo.repo /etc/yum.repos.d/mongo.repo
#
#dnf install mongodb-org -y
#
#sed -i 's/127.0.0.1/0.0.0.0/' /etc/mongod.conf
#
#systemctl enable mongod
#systemctl restart mongod

- name: frontend setup
  hosts: all
  become: true
  tasks:
    - name: Copy mongoDB repo file
      ansible.builtin.copy:
       src: mongo.repo
       dest: /etc/yum.repos.d/mongo.repo

    - name: Install mongoDB
      ansible.builtin.dnf:
        name: mongodb-org
        state: present

    - name: Replace "old_value" with "new_value" in /etc/config.conf
      ansible.builtin.replace:
        path: /etc/mongod.conf
        regexp: '127.0.0.1'
        replace: '0.0.0.0'

    - name: Start MongoDB service
      ansible.builtin.systemd_service:
        state: restarted
        name: mogodb
        enabled: true