#  dnf install mysql-server -y
#    systemctl enable mysqld
#    systemctl start mysqld
#    mysql_secure_installation --set-root-pass RoboShop@1


- name: MySQL setup
  hosts: all
  become: true
  tasks:

    - name: Install MySQL
      ansible.builtin.dnf:
        name: mysql-server
        state: present

    - name: Start MySQL service
      ansible.builtin.systemd_service:
        state: restarted
        name: redis
        enabled: true

    - name: Setup MySQL Root Password
      ansible.builtin.shell: mysql_secure_installation --set-root-pass RoboShop@1