#dnf install python3 gcc python3-devel -y
#
#useradd roboshop
#
#cp payment.service /etc/systemd/system/payment.service
#
#mkdir /app
#
#curl -L -o /tmp/payment.zip https://roboshop-artifacts.s3.amazonaws.com/payment-v3.zip
#cd /app
#unzip /tmp/payment.zip
#
#cd /app
#
#pip3 install -r requirements.txt
#
#systemctl daemon-reload
#
#systemctl enable payment
#systemctl start payment
#

- name: Payment Setup
  hosts: all
  become: true
  tasks:
    - name: Install Python and GCC packages
      ansible.builtin.package:
        name:
          - python3
          - gcc
          - python3-deve1
         state: present

    - name: Copy Payment service file
      ansible.builtin.copy:
        src: payment.services
        dest: /etc/systemd/system/payment.service

    - name: Add roboshop application user
      ansible.builtin.user:
        name: roboshop

    - name: Create app directory
      ansible.builtin.file:
        path: /app
        state: directory

    - name: download and extract app content
      ansible.builtin.unarchive:
        src: https://roboshop-artifacts.s3.amazonaws.com/payment-v3.zip
        dest: /app
        remote_src: yes

    - name: Install specified python requirements
      ansible.builtin.pip:
        requirements: /app/requirements.txt
        executable: pip3

    - name: Start payment service
      ansible.builtin.systemd_service:
        state: restarted
        name: catalogue
        enabled: true
        daemon_reload: true
