#dnf module disable redis -y
#dnf module enable redis:7 -y
#
#dnf install redis -y
#
#sed -i 's/127.0.0.1/0.0.0.0/g' /etc/redis/redis.conf
#
#sed -i '/protected-mode yes/c\protected-mode no' /etc/redis/redis.conf
#
#systemctl enable redis
#systemctl start redis

- name: Redis setup
  hosts: all
  become: true
  tasks:

    - name: Install Redis:7
      ansible.builtin.dnf:
        name: '@redis:7'
        state: present

    - name: Update Redis listen address
      ansible.builtin.replace:
        path: /etc/redis/redis.conf
        regexp: '127.0.0.1'
        replace: '0.0.0.0'

    - name: Disable Protected mode
      ansible.builtin.replace:
        path: /etc/redis/redis.conf
        regexp: 'protected-mode yes'
        replace: 'protected-mode no'

    - name: Start redis service
      ansible.builtin.systemd_service:
        state: restarted
        name: redis
        enabled: true